default_settings: null
behaviors: {}
env_settings:
  env_path: ..\..\..\..\Desktop\AI_selfdriveable_car.exe
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 512
  height: 512
  quality_level: 0
  time_scale: 10.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: AI_selfdriveable_car_1
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
debug: false
